### ISSUE TITLE
Single stepping over memset hangs

### ISSUE THREAD

**Issue by neon12345** [rr-debugger/rr#2797] opened 2021-01-21 01:23 UTC
When single stepping over memset, it seems as if rr is stuck at the marked line trying to get to the next event.

__memset_avx2_erms:
00007f173e056b00:   vzeroupper      
00007f173e056b03:   mov     %rdx,%rcx
00007f173e056b06:   movzbl  %sil,%eax
00007f173e056b0a:   mov     %rdi,%rdx
00007f173e056b0d:   rep     stos %al,%es:(%rdi)                            <----- SIGTRAP?
00007f173e056b0f:   mov     %rdx,%rax
00007f173e056b12:   retq

example bzero.c:

```
#include <string.h>

int test[4096 << 3];
int main() { 
        memset(&test, 0, sizeof(test)); 
        return test[0];
}
```
clang -O1 -g3 -fno-builtin  bzero.c -o bzero

rr is latest master on stock debian stable, x86_64.

**Comment by rocallahan** [comment] 2021-01-21 01:27
Does this happen in gdb without rr?

**Comment by neon12345** [comment] 2021-01-21 01:30
no

**Comment by rocallahan** [comment] 2021-01-21 02:05
Can you give me a complete log of the gdb commands you use with rr?

**Comment by neon12345** [comment] 2021-01-21 02:15
tui enable
layout asm
break main
c
watch $rsp
c
c
...
Ctrl+C

or break at main and use stepi

**Comment by rocallahan** [comment] 2021-01-21 02:19
With those commands I end up in some dl_runtime_resolve stuff. Can you paste a complete log of your gdb session?

**Comment by neon12345** [comment] 2021-01-21 02:25
you can try:

break __memset_avx2_erms
stepi

**Comment by rocallahan** [comment] 2021-01-21 02:38
Here's what I get under gdb with or without rr:
```
(gdb) break *0x00007ffff7f40811
Breakpoint 3 at 0x7ffff7f40811: file ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S, line 141.
(gdb) c
Continuing.

Breakpoint 3, __memset_avx2_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:141
141		rep stosb
(gdb) disass
Dump of assembler code for function __memset_avx2_erms:
   0x00007ffff7f40800 <+0>:	endbr64 
   0x00007ffff7f40804 <+4>:	vzeroupper 
   0x00007ffff7f40807 <+7>:	mov    %rdx,%rcx
   0x00007ffff7f4080a <+10>:	movzbl %sil,%eax
   0x00007ffff7f4080e <+14>:	mov    %rdi,%rdx
=> 0x00007ffff7f40811 <+17>:	rep stos %al,%es:(%rdi)
   0x00007ffff7f40813 <+19>:	mov    %rdx,%rax
   0x00007ffff7f40816 <+22>:	ret    
End of assembler dump.
(gdb) print $rcx
$1 = 131072
(gdb) stepi

Breakpoint 3, __memset_avx2_erms () at ../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:141
141		rep stosb
(gdb) disass
Dump of assembler code for function __memset_avx2_erms:
   0x00007ffff7f40800 <+0>:	endbr64 
   0x00007ffff7f40804 <+4>:	vzeroupper 
   0x00007ffff7f40807 <+7>:	mov    %rdx,%rcx
   0x00007ffff7f4080a <+10>:	movzbl %sil,%eax
   0x00007ffff7f4080e <+14>:	mov    %rdi,%rdx
=> 0x00007ffff7f40811 <+17>:	rep stos %al,%es:(%rdi)
   0x00007ffff7f40813 <+19>:	mov    %rdx,%rax
   0x00007ffff7f40816 <+22>:	ret    
End of assembler dump.
(gdb) print $rcx
$2 = 131071
```
This is what I expect. Every `stepi` executes `stosb` once, decreasing RCX by 1, so it will take 131072 singlesteps before we get past this instruction.

Either I still misunderstand what you actually are trying to do here, or you made a mistake when you said this doesn't happen under gdb.

**Comment by neon12345** [comment] 2021-01-21 03:01
I initially thought it was stuck because it takes very long with high CPU usage in another program. If I break at __memset_avx2_erms and continue, I would assume that rr SIGTRAPs at the next syscall event but instead it seems to trap at this instruction every time?!

**Comment by rocallahan** [comment] 2021-01-21 03:19
Sometimes you talk about "continue" and sometimes you talk about "single stepping", so I'm confused and I still don't understand exactly what you are doing that you think triggers a bug.

Please give me a complete log of your rr replay session.

**Comment by neon12345** [comment] 2021-01-21 03:36
The full story is, I created a simple python script with watchpoints that basically does "watch $rip", prints some function information and continues. At some point the output stopped and CPU went very high. I then attached to the rr process with gdb and realized that it continously gets SIGTRAPS and does not progress to the next event.

How do I get a complete log of the replay session?

**Comment by rocallahan** [comment] 2021-01-21 03:39
And you ran that script with gdb, without rr, and it didn't have this problem?

**Comment by rocallahan** [comment] 2021-01-21 03:40
Maybe you can provide that script and instructions on how to run it on your bzero example in a way that reproduces the bug with rr and works fine without rr?

**Comment by neon12345** [comment] 2021-01-21 04:02
If you do:

```
break __memset_avx2_erms
c
watch $rsp
c
```

gdb is significantly faster with my machine and bzero, thats why I thought gdb does not have this problem. But I think it is not a real bug then.

**Comment by rocallahan** [comment] 2021-01-21 04:40
OK I see what's going on.

When you do `watch $rsp`, gdb has to singlestep the program to check the value of RSP at each step. Those individual singlesteps are slower under rr for various reasons. You can see a similar effect if you measure the time taken by 'stepi 10000` (e.g. starting at `main`). On my machine I get:

* debug build of rr: about 6 seconds
* release build of rr: about 5 seconds
* gdb via gdbserver: about 3 seconds
* regular gdb: about 1 second

So I think probably a significant chunk of the rr overhead is just the overhead of being a remote gdb server instead of doing all the debugging in the single gdb process.

**Comment by rocallahan** [comment] 2021-01-21 04:42
There might be something we can do to speed this up but since it's not a hang, just slow, I'm going to close this.

**Closed by rocallahan** 2021-01-21 04:42 UTC
