### ISSUE TITLE
undefined reference to `__x86.get_pc_thunk.ax'

### ISSUE THREAD

**Issue by GitMensch** [rr-debugger/rr#2936] opened 2021-07-22 08:18 UTC
~~~
Scanning dependencies of target exit_status_32
[ 20%] Linking C executable bin/fork_stress_32
[ 20%] Built target ignored_sigsegv_32
[ 20%] Linking C executable bin/fd_limit_32
[ 20%] Linking C executable bin/fork_syscalls_32
[ 20%] Building C object CMakeFiles/exit_status_32.dir/32/exit_status.c.o
[ 20%] Built target function_calls_32
CMakeFiles/fxregs_32.dir/32/x86/fxregs.c.o: In function `main':
/tmp/rr-obj/32/x86/fxregs.c:64: undefined reference to `__x86.get_pc_thunk.ax'
collect2: error: ld returned 1 exit status
~~~

Work-around: clear all generated objects, then start again with `CC=gcc cmake -Ddisable32bit=ON`.

**Comment by khuey** [comment] 2021-07-26 00:16
This is a dupe of #2927

**Closed by khuey** 2021-07-26 00:16 UTC
